### ISSUE TITLE
Rename/rebrand our icon set(s)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#11]
We agree that "NPMaki" doesn't quite work as a name for our web map icons. Prior to a formal release complete with a landing page in the Tools section of the website, we need to come up with a succinct and original name.

**Comment by jakecoolidge** [comment]
A couple initial ideas: 
- NPSymbols
- NPMapIcons

Generic, I know. I'll be thinking about this over the next couple of days.

**Comment by makella** [comment]
I was talking with Juan today about how we are trying to think of another name for NPMaki.  One thing he suggested (that I think is good food for thought) is just Symbol Library.  It was interesting to talk to him because he said a lot of people don't know what icons/symbology/etc actually are (didn't realize that!).  He was saying words like signage to define icons. 

Anyway, just wanted to add his thought here to the conversation.  It was good to talk to someone that isn't in the mapping field to get a different perspective.

**Comment by jakecoolidge** [comment]
I'm glad you guys talked about it--outside perspective is typically a good thing. I actually never gave up on using "Symbols" somewhere in the name. And I am definitely allergic to using "Symbology". "Symbol Library" is nice. Let's percolate on it and return to it next week.

**Comment by jakecoolidge** [comment]
Moving forward with Symbol Library.
