### ISSUE TITLE
New symbols for review

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#28]
Please have a look at the attached images (72ppi and 150ppi versions available). These are my current working designs for some of the symbols in our new icon list. Submit your feedback here, and I'll develop a second iteration. Thanks!

![npmap-symbol-library-proposed-additions-01](https://cloud.githubusercontent.com/assets/11392872/9147019/f2c05f00-3d1e-11e5-9dd1-c3171845caa1.png)
_72 ppi version_

![npmap-symbol-library-proposed-additions-150ppi-01](https://cloud.githubusercontent.com/assets/11392872/9147040/1bca60b2-3d1f-11e5-88e1-d4951f4ffc11.png)
_150 ppi version_

**Comment by jimmyrocks** [comment]
These look great! I can't wait for them to get added in iD!

**Comment by makella** [comment]
@jakecoolidge these look good! 

The one symbol that I think can be easily misinterpreted is the RR crossing symbol for Builder.  And maybe the RR crossing symbol you have for Park Tiles as well. In emergency/incident management a circle with a X around it indicates the location of origin. I could see in some parks (especially the natural ones) that confusion could arise.  One idea might be to try and put the R's in on each side of the X.  In Places Mobile FOSM, the RR crossing symbol was colored to look like the one on the ground because those maps are meant to be a little more illustrative and represent features as they appear to visitors (for the most part).

Also, on the white icon for laundry it looks like the circle around the washing bin is missing. 

For the flagpole, I'd go with the non-wavy version to reduce complexity.

**Comment by mtaylorlong** [comment]
I'll second Mamata's feedback.

I'm sure y'all have discussed this quite a bit in the past, but I have a had time imagining using the smallest versions of these – the 16px Park Tiles symbols are barely legible (some of them do pull it off), but the 12px Builder symbols are basically impossible to read. 

Are there any maps in which we use these smallest symbols?
