### ISSUE TITLE
Create geyser icon

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/symbol-library#30]
Now that we're working on two projects for Yellowstone, we really need a geyser icon!

**Comment by jakecoolidge** [comment]
I started doing some digging around on this. I learned that HFC uses a generic purple circle marker for "geothermal features" on their Yellowstone map, which makes sense when you visit [nps.gov/yell](http://www.nps.gov/yell/learn/nature/hydrothermal-features.htm) and see that the park highlights several features within a category called "hydrothermal features": hot springs, mudpots, fumaroles (or steam vents), travertine terraces, and geysers.

My question to the group: are we better served by creating a geothermal/hydrothermal feature symbol, or is there enough interest to single out geysers as landmarks and not worry about symbolizing the other features? Owing to the visibility of geysers, this type is the only hydrothermal feature to make it onto our presets list. By contrast, mudpots did not make the cut.

Are there any parks that allow people to use hot springs for bathing? If so, this may be an amenity to map separately from other more hazardous hydrothermal features.

**Comment by nateirwin** [comment]
Some parks do allow bathing in hot springs, although most of them are trying to do away with this practice. GRTE is an example of this.

Perhaps we should ask HFC what they think?

**Comment by jakecoolidge** [comment]
I may consult HFC; I haven't bugged them for a while. I'm also considering talking to staff at Yellowstone about it, since their park will make the most of the symbol. I imagine a few parks in PWR and AKR also have hydrothermal features, but I think of them as more of a key feature/attraction at Yellowstone. @nateirwin if you think of a good contact person at the park I could get in touch with, let me know.

**Comment by jakecoolidge** [comment]
closing since it doesn't appear that YELL will need this symbol after all
